services:
  - docker

language: go
arch:
  - amd64
  - arm64
go:
  - 1.10.8

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
    - /^PR\d*$/
    - /.*/

env:
  global:
    - REPO=cloudnativelabs/kube-router
    - REPO_PATH=$HOME/gopath/src/github.com/$REPO
    - GIT_BRANCH=$TRAVIS_BRANCH

script:
  - build/travis-test.sh
  # All successfully built commits get an image placed in the kube-router-git
  # image repo and tagged with the commit hash.
  - if [ "${TRAVIS_CPU_ARCH}" == "arm64" ]; then
      wget https://github.com/estesp/manifest-tool/releases/download/v1.0.2/manifest-tool-linux-arm64 -O manifest-tool && chmod +x manifest-tool;
    else
      wget https://github.com/estesp/manifest-tool/releases/download/v1.0.2/manifest-tool-linux-amd64 -O manifest-tool && chmod +x manifest-tool;
    fi
  - build/travis-deploy.sh

# This fixes issues when a contributor uses their own Travis CI account to test
# code/CI changes.
before_install:
  - mkdir -p $REPO_PATH
  - rsync -az ${TRAVIS_BUILD_DIR}/ $REPO_PATH
  - export TRAVIS_BUILD_DIR=$REPO_PATH
  - cd $REPO_PATH
